"""remove first_run from user_preferences

Revision ID: 027abed83f89
Revises: 8d1d2b2af3d6
Create Date: 2025-04-18 13:21:30.548666

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '027abed83f89'
down_revision: Union[str, None] = '8d1d2b2af3d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_preferences') as batch_op:
        batch_op.drop_column('calories_enabled')
        batch_op.drop_column('healthy_mode')
        batch_op.add_column(sa.Column('healthy_profile', sa.Boolean(), server_default=sa.false(), nullable=False))
        batch_op.add_column(sa.Column('preferred_cuisine', sa.String(), server_default='Любая', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
